"""empty message

Revision ID: 09696e8a708c
Revises: 1fa172552aaa
Create Date: 2023-03-12 23:39:16.375089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09696e8a708c'
down_revision = '1fa172552aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
