"""empty message

Revision ID: 408f187cadf2
Revises: e2d98cbf4a05
Create Date: 2023-03-13 00:22:19.635670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408f187cadf2'
down_revision = 'e2d98cbf4a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
