"""empty message

Revision ID: 46876fd888ea
Revises: 51a5b18739c6
Create Date: 2023-03-11 18:00:58.845391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46876fd888ea'
down_revision = '51a5b18739c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
